// Next.jsのメタデータ型をインポート - ページのメタ情報を定義するために使用
import type { Metadata } from "next";
// Next.jsのフォント最適化機能を使用してGeistフォントをインポート
import { Geist, Geist_Mono } from "next/font/google";
// グローバルCSSをインポート - アプリケーション全体に適用されるスタイル
import "./globals.css";

// Geistサンセリフフォントを設定 - モダンでクリーンなUIに適したフォント
const geistSans = Geist({
  variable: "--font-geist-sans", // CSSカスタムプロパティ名を指定 - TailwindCSSなどで参照可能
  subsets: ["latin"], // ラテン文字のサブセットのみを読み込み - パフォーマンス最適化
});

// Geistモノスペースフォントを設定 - コードブロックやテクニカルな表示に適したフォント
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSSカスタムプロパティ名を指定
  subsets: ["latin"], // ラテン文字のサブセットのみを読み込み
});

// アプリケーションのメタデータを設定 - SEOやソーシャルシェアに重要
export const metadata: Metadata = {
  title: "Create Next App", // ブラウザのタブに表示されるタイトル
  description: "Generated by create next app", // 検索エンジンやソーシャルシェア時に表示される説明文
};

// ルートレイアウトコンポーネント - アプリケーション全体の共通レイアウトを定義
export default function RootLayout({
  children, // 子コンポーネント（ページコンテンツ）
}: Readonly<{
  children: React.ReactNode; // 子要素の型定義 - Reactノード（JSX要素、文字列、数値など）
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // フォント変数とアンチエイリアス設定を適用
      >
        {children} {/* ページコンテンツをレンダリング */}
      </body>
    </html>
  );
}